<?php

namespace ITCity\Rivile\Objects;

class Client extends Object {
	protected static $prefix = 'N08';

	protected static $defs = [
		'N08_KODAS_KS' => ['string', 'max:12'],
		'N08_RUSIS' => ['integer', 'in:1,2,3,4'],
		'N08_PVM_KODAS' => ['string', 'max:25'],
		'N08_IM_KODAS' => ['string', 'max:13'],
		'N08_PAV' => ['string', 'max:70'],
		'N08_ADR' => ['string', 'max:40'],
		'N08_KODAS_VS' => ['string', 'max:12'],
		'N08_PASTAS' => ['string', 'max:9'],
		'N08_ATSTOVAS' => ['string', 'max:40'],
		'N08_E_MAIL' => ['string', 'max:40'],
		'N08_FAX_NUM' => ['string', 'max:40'],
		'N08_TEL' => ['string', 'max:40'],
		'N08_MOB_TEL' => ['string', 'max:40'],
		'N08_KODAS_LS_1' => ['string', 'max:12'],
		'N08_KODAS_LS_2' => ['string', 'max:12'],
		'N08_KODAS_LS_3' => ['string', 'max:12'],
		'N08_KODAS_LS_4' => ['string', 'max:12'],
		'N08_TIPAS_PIRK' => ['integer', 'min:1', 'max:2'],
		'N08_TIPAS_TIEK' => ['integer', 'min:1', 'max:2'],
		'N08_KODAS_GS' => ['string', 'max:12'],
		'N08_CREDIT_LIM' => ['numeric', 'max:9999999999.99'],
		'N08_KODAS_DS' => ['string', 'max:12'],
		'N08_DELSPINIGIAI' => ['numeric', 'max:999.99'],
		'N08_KODAS_QS' => ['string', 'max:12'],
		'N08_NUOL_GR' => ['string', 'max:6'],
		'N08_KODAS_XS_T' => ['string', 'max:12'],
		'N08_KODAS_XS_P' => ['string', 'max:12'],
		'N08_KODAS_TS_T' => ['string', 'max:12'],
		'N08_KODAS_TS_P' => ['string', 'max:12'],
		'N08_ADD_DATE' => ['date'],
		'N08_SUTARTIS' => ['boolean'],
		'N08_KAIN_ABC' => ['boolean'],
		'N08_DIENOS' => ['boolean'],
		'N08_TIEK_DIEN' => ['boolean'],
		'N08_KRED_LIM' => ['boolean'],
		'N08_PRIEDAI' => ['boolean'],
		'N08_KODAS_IS' => ['string', 'max:12'],
		'N08_KODAS_OS_P' => ['string', 'max:12'],
		'N08_KODAS_OS' => ['string', 'max:12'],
		'N08_KODAS_MS_P' => ['string', 'max:12'],
		'N08_KODAS_MS_T' => ['string', 'max:12'],
		'N08_VAL_POZ' => ['boolean'],
		'N08_KODAS_VL_1' => ['string', 'max:12'],
		'N08_KODAS_VL_2' => ['string', 'max:12'],
		'N08_KODAS_VL_3' => ['string', 'max:12'],
		'N08_KODAS_VL_4' => ['string', 'max:12'],
		'N08_KODAS_VL_5' => ['string', 'max:12'],
		'N08_KODAS_VL_6' => ['string', 'max:12'],
		'N08_POZ_DATE' => ['boolean'],
		'N08_BEG_DATE' => ['date'],
		'N08_END_DATE' => ['date'],
		'N08_ADDUSR' => ['string', 'max:12'],
		'N08_USERIS' => ['string', 'max:12'],
		'N08_R_DATE' => ['date'],
		'N08_GER_POZ' => ['boolean'],
		'N08_KODAS_LS_5' => ['string', 'max:12'],
		'N08_KODAS_LS_6' => ['string', 'max:12'],
		'N08_KODAS_LS_7' => ['string', 'max:12'],
		'N08_KODAS_LS_8' => ['string', 'max:12'],
		'N08_T_LIM_POZ' => ['boolean'],
		'N08_T_KRED_LIM' => ['numeric', 'max:9999999999.99'],
		'N08_KODAS_VL_LIM' => ['string', 'max:12'],
		'N08_KAINYNAS' => ['string', 'max:1'],
		'N08_AR_REIK_P' => ['boolean'],
		'N08_AR_REIK_T' => ['boolean'],
		'N08_REZERVAS' => ['string', 'max:40'],
		'N08_INTRASTAT' => ['boolean'],
		'N08_WB_KR' => ['boolean'],
		'N08_WB_KR_GR' => ['boolean'],
		'N08_SUMA_WK_LIMIT' => ['numeric', 'max:9999999999.99'],
		'N08_SUMA_WK' => ['numeric', 'max:9999999999.99'],
		'N08_KODAS_VL_U' => ['string', 'max:12'],
	];
}