<?php

namespace ITCity\Rivile\Objects;

class Client extends Object {
	protected static $prefix = 'N08';

	protected static $defs = [
		'n08_kodas_ks' => ['string', 'max:12'],
		'n08_rusis' => ['integer', 'in:1,2,3,4'],
		'n08_pvm_kodas' => ['string', 'max:25'],
		'n08_im_kodas' => ['string', 'max:13'],
		'n08_pav' => ['string', 'max:70'],
		'n08_adr' => ['string', 'max:40'],
		'n08_kodas_vs' => ['string', 'max:12'],
		'n08_pastas' => ['string', 'max:9'],
		'n08_atstovas' => ['string', 'max:40'],
		'n08_e_mail' => ['string', 'max:40'],
		'n08_fax_num' => ['string', 'max:40'],
		'n08_tel' => ['string', 'max:40'],
		'n08_mob_tel' => ['string', 'max:40'],
		'n08_kodas_ls_1' => ['string', 'max:12'],
		'n08_kodas_ls_2' => ['string', 'max:12'],
		'n08_kodas_ls_3' => ['string', 'max:12'],
		'n08_kodas_ls_4' => ['string', 'max:12'],
		'n08_tipas_pirk' => ['integer', 'min:1', 'max:2'],
		'n08_tipas_tiek' => ['integer', 'min:1', 'max:2'],
		'n08_kodas_gs' => ['string', 'max:12'],
		'n08_credit_lim' => ['numeric', 'max:9999999999.99'],
		'n08_kodas_ds' => ['string', 'max:12'],
		'n08_delspinigiai' => ['numeric', 'max:999.99'],
		'n08_kodas_qs' => ['string', 'max:12'],
		'n08_nuol_gr' => ['string', 'max:6'],
		'n08_kodas_xs_t' => ['string', 'max:12'],
		'n08_kodas_xs_p' => ['string', 'max:12'],
		'n08_kodas_ts_t' => ['string', 'max:12'],
		'n08_kodas_ts_p' => ['string', 'max:12'],
		'n08_add_date' => ['date'],
		'n08_sutartis' => ['boolean'],
		'n08_kain_abc' => ['boolean'],
		'n08_dienos' => ['boolean'],
		'n08_tiek_dien' => ['boolean'],
		'n08_kred_lim' => ['boolean'],
		'n08_priedai' => ['boolean'],
		'n08_kodas_is' => ['string', 'max:12'],
		'n08_kodas_os_p' => ['string', 'max:12'],
		'n08_kodas_os' => ['string', 'max:12'],
		'n08_kodas_ms_p' => ['string', 'max:12'],
		'n08_kodas_ms_t' => ['string', 'max:12'],
		'n08_val_poz' => ['boolean'],
		'n08_kodas_vl_1' => ['string', 'max:12'],
		'n08_kodas_vl_2' => ['string', 'max:12'],
		'n08_kodas_vl_3' => ['string', 'max:12'],
		'n08_kodas_vl_4' => ['string', 'max:12'],
		'n08_kodas_vl_5' => ['string', 'max:12'],
		'n08_kodas_vl_6' => ['string', 'max:12'],
		'n08_poz_date' => ['boolean'],
		'n08_beg_date' => ['date'],
		'n08_end_date' => ['date'],
		'n08_addusr' => ['string', 'max:12'],
		'n08_useris' => ['string', 'max:12'],
		'n08_r_date' => ['date'],
		'n08_ger_poz' => ['boolean'],
		'n08_kodas_ls_5' => ['string', 'max:12'],
		'n08_kodas_ls_6' => ['string', 'max:12'],
		'n08_kodas_ls_7' => ['string', 'max:12'],
		'n08_kodas_ls_8' => ['string', 'max:12'],
		'n08_t_lim_poz' => ['boolean'],
		'n08_t_kred_lim' => ['numeric', 'max:9999999999.99'],
		'n08_kodas_vl_lim' => ['string', 'max:12'],
		'n08_kainynas' => ['string', 'max:1'],
		'n08_ar_reik_p' => ['boolean'],
		'n08_ar_reik_t' => ['boolean'],
		'n08_rezervas' => ['string', 'max:40'],
		'n08_intrastat' => ['boolean'],
		'n08_wb_kr' => ['boolean'],
		'n08_wb_kr_gr' => ['boolean'],
		'n08_suma_wk_limit' => ['numeric', 'max:9999999999.99'],
		'n08_suma_wk' => ['numeric', 'max:9999999999.99'],
		'n08_kodas_vl_u' => ['string', 'max:12'],
	];
}